[tool.black]
line-length = 120
target-version = ['py311']

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true
fail_under = 90
precision = 2
sort = "Miss"

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true

[tool.isort]
profile = "black"
