"""initial migration

Revision ID: 05605bf2b47d
Revises:
Create Date: 2023-01-06 13:45:04.368409

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "05605bf2b47d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "building",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("event_timestamp", sa.BigInteger(), nullable=True),
        sa.Column("building_id", sa.String(), nullable=False),
        sa.Column("building_name", sa.String(), nullable=False),
        sa.Column(
            "building_type",
            sa.Enum(
                "Commercial_Office",
                "Commercial_Other",
                "Commercial_Retail",
                "Cultural",
                "Educational",
                "Government",
                "Healthcare",
                "Hospitality",
                "Residential_Multi_Family",
                "Residential_Single_Family",
                name="buildingtype",
            ),
            nullable=False,
        ),
        sa.Column("street", sa.String(), nullable=False),
        sa.Column("house", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("building_id"),
    )
    op.create_table(
        "room",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("event_timestamp", sa.BigInteger(), nullable=False),
        sa.Column("room_id", sa.String(), nullable=False),
        sa.Column("building_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("floor_number", sa.Integer(), nullable=False),
        sa.Column("function", sa.Enum("office", "meeting", "recreation", "other", name="roomfunction"), nullable=False),
        sa.PrimaryKeyConstraint("room_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("room")
    op.execute("DROP TYPE roomfunction")
    op.drop_table("building")
    op.execute("DROP TYPE buildingtype")
    # ### end Alembic commands ###
